#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
typedef long double ld;
typedef pair<int, int> pii;
typedef pair<ll, ll> pll;
typedef vector<int> vi;
typedef vector<ll> vl; 
typedef vector<bool> vb;
typedef vector<ld> vd;
typedef vector<vector<int>> vvi;
typedef vector<vector<ll>> vvl;
typedef vector<vector<bool>> vvb;
typedef vector<vector<ld>> vvd;
// typedef __int128 lll;
// typedef __float128 lld;

//Codeforces - 2234D

//let x = a[1], y = a[2^k + 1]
//observe that all values generated by the process are in {0, x, y, xy}
//actually, 0 is never generated.
//by doing some examples, we can come up with the following dp:

// dp1[i] = value of [x, y] given i steps
// dp2[i] = value of [x, xy] given i steps
// dp3[i] = value of [y, xy] given i steps

// dp1[0] = val(x) + val(y)
// dp2[0] = val(x) + val(xy)
// dp3[0] = val(y) + val(xy)

// dp1[i] = dp2[i - 1] + dp3[i - 1] - val(xy)
// dp2[i] = dp1[i - 1] + dp3[i - 1] - val(y)
// dp3[i] = dp1[i - 1] + dp2[i - 1] - val(x)

// ans = dp1[k]

ll calcv(string x) {
    ll zcnt = 0, ocnt = 0;
    for(int i = 0; i < x.size(); i++) {
        if(x[i] == '0') zcnt ++;
        else ocnt ++;
    }
    return zcnt * ocnt;
}

signed main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL); cout.tie(NULL);
    
    int t;
    cin >> t;
    while(t--) {
        int n, k;
        cin >> n >> k;
        string x, y, xy(n, ' ');
        cin >> x >> y;
        for(int i = 0; i < n; i++) xy[i] = (x[i] == y[i]? '0' : '1');
        ll vx = calcv(x), vy = calcv(y), vxy = calcv(xy);
        vl dp1(k + 1), dp2(k + 1), dp3(k + 1);
        dp1[0] = vx + vy;
        dp2[0] = vx + vxy;
        dp3[0] = vy + vxy;
        for(int i = 1; i <= k; i++) {
            dp1[i] = dp2[i - 1] + dp3[i - 1] - vxy;
            dp2[i] = dp1[i - 1] + dp3[i - 1] - vy;
            dp3[i] = dp1[i - 1] + dp2[i - 1] - vx;
        }
        cout << dp1[k] << "\n";
    }
    
    return 0;
}